### ISSUE TITLE
Peserve Metadata

### ISSUE THREAD

**Issue by Alban9** [DavidAnson/ConvertTo-Jpeg#11] opened 2020-08-18 21:14 UTC
When converting a HEIC photo to a JPG photo some metadata is lost. For example the date taken which for me is very important. So without that feature I can not use this tool. I do not know how it could be implemented easily.

**Comment by DavidAnson** [comment] 2020-08-18 22:00
Duplicate of #3

**Closed by DavidAnson** 2020-08-18 22:00 UTC
