### ISSUE TITLE
No suitable transform was found to encode or decode the content

### ISSUE THREAD

**Issue by AdrianbCojocaru** [DavidAnson/ConvertTo-Jpeg#22] opened 2024-06-29 13:13 UTC
`powershell.exe -executionpolicy bypass -file ConvertTo-Jpeg.ps1 -files "IMG_0923.HEIC"`
System.Management.Automation.MethodInvocationException: Exception calling "Wait" with "0" argument(s): "One or more
errors occurred." ---> System.AggregateException: One or more errors occurred. ---> System.Exception: No suitable
transform was found to encode or decode the content. (Exception from HRESULT: 0xC00D5212)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At C:\Users\adria\Downloads\poze-20240629T125809Z-001\ConvertTo-Jpeg.ps1:121 char:13
+             throw $_.Exception.ToString()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (System.Manageme...tedFrame frame):String) [], RuntimeException
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException: Exception calling "Wait" with "0
   " argument(s): "One or more errors occurred." ---> System.AggregateException: One or more errors occurred. ---> Sy
  stem.Exception: No suitable transform was found to encode or decode the content. (Exception from HRESULT: 0xC00D52
 12)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Excepti
   on exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by DavidAnson** [comment] 2024-06-29 16:13
Duplicate of: https://github.com/DavidAnson/ConvertTo-Jpeg/issues/12

**Closed as not planned** 2024-10-05 20:36 UTC
Labels: question
